apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-frontend
  template:
    metadata:
      labels:
        app: f1-frontend
    spec:
      containers:
        - name: f1-frontend
          image: gtr55/f1-frontend:latest
          ports:
            - containerPort: 3000
